name: ps_check
description: ps-check

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: "^3.3.0"

dependencies:
  http: ^1.2.1
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.0.8
  html: ^0.15.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0
  async: ^2.8.2
  #firebase_messaging: 10.0.7
  workmanager: ^0.5.0
  flutter_local_notifications: ^17.1.0
  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1
  auto_size_text: ^3.0.0-nullsafety.0
  loading_animation_widget: ^1.2.1
  #page_transition: ^2.0.2
  #feature_discovery: 0.14.0
  #introduction_screen: ^2.1.0
  #url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  tutorial_coach_mark: ^1.2.3
  flutter_slidable: ^3.0.0
  flutter_app_badger: ^1.3.0
  tap_debouncer: ^2.0.0
  fluttertoast: ^8.0.8
  synchronized: ^3.0.0
  transparent_image: ^2.0.0
  toggle_switch: ^2.0.1
  provider: ^6.0.3
  glass_kit: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  sliver_header_delegate: ^0.0.5
#  webview_flutter: ^2.1.2
#  webview_cookie_manager: ^2.0.6
#  webview_flutter: ^4.7.0

#  objectbox: ^1.2.0
#  objectbox_flutter_libs: any

#  isar: ^0.4.0
#  isar_flutter_libs: ^0.4.0 # contains the binaries

#  json_annotation: ^4.0.1

  #  pull_to_refresh: ^1.6.5
  #settings_ui: 0.6.0
  #shared_preferences_settings: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

#dependency_overrides:
#  flutter_inappwebview:
#    git:
#      url: https://github.com/CodeEagle/flutter_inappwebview

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  #provider: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1

#  objectbox_generator: ^1.2.0

#  isar_generator: ^0.4.0

  #json_serializable: 4.1.0

flutter_icons:
      ios: true
      android: true
      image_path_ios: "asset/icon.jpg"
      image_path_android: "asset/icon.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
